version: '3.9'

services:
  backend:
    build: ./Django   
    restart: unless-stopped
    depends_on:
      - database
  database:
    image: postgres:13.0-alpine
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  nginx:
    build: ./Nginx
    restart: unless-stopped
    ports:
      - 6791:8080
    depends_on:
      - backend


volumes:
  postgres_data:
